apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: client-go
build:
  artifacts:
  - image: akicontport/mc-operator
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/ns.yaml
