---
apiVersion: v1
kind: Namespace
metadata:
  name: mc-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mc-admin
  namespace: mc-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mc-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mc-admin-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mc-admin
subjects:
- kind: ServiceAccount
  name: mc-admin
  namespace: mc-operator
#  kubectl auth can-i get pods --as=system:serviceaccount:mc-operator:mc-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mc-operator
  name: mc-operator
  namespace: mc-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mc-operator
    spec:
      serviceAccountName: mc-admin
      containers:
      - image: akicontport/mc-operator
        name: mc-operator
